fos.user:
    resource: "@Fos_UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_bundle:
   resource: "@Fos_UserBundle/Resources/config/routing.yml"